// Contacts (Cari) module contracts — DTOs, permission keys, service interfaces
// and their axios clients. Re-exported from the shared barrel.
export * from './contacts.permissions'
export * from './contact.dto'
export * from './contact-transaction.dto'
export * from './activity.dto'
export * from './opportunity.dto'
export * from './pipeline.dto'
export * from './crm-analytics.dto'
export * from './notification.dto'
export * from './crm-fields.dto'
export * from './integrations.dto'

export * from './contacts.service'
export * from './contacts.client'
export * from './contact-groups.service'
export * from './contact-groups.client'
export * from './contact-persons.service'
export * from './contact-persons.client'
export * from './contact-addresses.service'
export * from './contact-addresses.client'
export * from './contact-transactions.service'
export * from './contact-transactions.client'
export * from './activities.service'
export * from './activities.client'
export * from './opportunities.service'
export * from './opportunities.client'
export * from './pipelines.service'
export * from './pipelines.client'
export * from './crm-analytics.service'
export * from './crm-analytics.client'
export * from './notifications.service'
export * from './notifications.client'
export * from './crm-fields.service'
export * from './crm-fields.client'
export * from './integrations.service'
export * from './integrations.client'
